# Site settings
title: 荆凉凉
description: '君子不器' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://stpjing.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/MVM-logo-full.svg"
logo-icon: "/assets/img/branding/MVM-symbol.svg"
logo-icon-SEO: "/assets/img/branding/MVM-symbol-black.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/MVM-logo-full-dark.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# Author settings
#我不理解
#
author: 荆凉凉 # add your name
author-pic: Myself_Neon_grey.jpg
about-author: 在校大学生.

# Contact links
email: youngloogjim@gmail.com # Add your Email address
phone: +86 19982040169 # Add your Phone number
website: https://stpjing.github.io # Add your website
#linkedin: stpJing # Add your Linkedin handle
github: stpJing # Add your Github handle
#twitter: '@MvmThe' # Add your Twitter handle
#bandcamp: armandomaynez # Add your Bandcamp username
stackoverflow: stpjing # Add your stackoverflow account

# Newsletter
mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"


#Livere
livere_uid: MTAyMC81NjM3My8zMjgzNg==
#换掉
# Disqus
#discus_identifier: amaynez-github-io # Add your discus identifier
#comments_curtain: yes # leave empty to show the disqus embed directly


#百度统计
baiduID: e48a87a2aa086c04d51b92ee5320c82a
# Tracker
#谷歌统计
# analytics: G-R8SZS2YBZK
# fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
